// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pkg/proto/kvpb/service/kvservice.proto

package kvpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_pkg_proto_kvpb_service_kvservice_proto protoreflect.FileDescriptor

const file_pkg_proto_kvpb_service_kvservice_proto_rawDesc = "" +
	"\n" +
	"&pkg/proto/kvpb/service/kvservice.proto\x12\x04kvpb\x1a$pkg/proto/kvpb/common/requests.proto\x1a%pkg/proto/kvpb/common/responses.proto\x1a\x1apkg/proto/kvpb/kv/kv.proto\x1a,pkg/proto/kvpb/transaction/transaction.proto\x1a pkg/proto/kvpb/watch/watch.proto2\xe4\x05\n" +
	"\tKVService\x12*\n" +
	"\x03Get\x12\x10.kvpb.GetRequest\x1a\x11.kvpb.GetResponse\x12*\n" +
	"\x03Put\x12\x10.kvpb.PutRequest\x1a\x11.kvpb.PutResponse\x123\n" +
	"\x06Delete\x12\x13.kvpb.DeleteRequest\x1a\x14.kvpb.DeleteResponse\x128\n" +
	"\n" +
	"PutWithTTL\x12\x17.kvpb.PutWithTTLRequest\x1a\x11.kvpb.PutResponse\x12N\n" +
	"\x0fGetWithRevision\x12\x1c.kvpb.GetWithRevisionRequest\x1a\x1d.kvpb.GetWithRevisionResponse\x12?\n" +
	"\n" +
	"GetHistory\x12\x17.kvpb.GetHistoryRequest\x1a\x18.kvpb.GetHistoryResponse\x120\n" +
	"\x05Range\x12\x12.kvpb.RangeRequest\x1a\x13.kvpb.RangeResponse\x126\n" +
	"\aCompact\x12\x14.kvpb.CompactRequest\x1a\x15.kvpb.CompactResponse\x12*\n" +
	"\x03Txn\x12\x10.kvpb.TxnRequest\x1a\x11.kvpb.TxnResponse\x12/\n" +
	"\x05Watch\x12\x12.kvpb.WatchRequest\x1a\x10.kvpb.WatchEvent0\x01\x126\n" +
	"\aUnwatch\x12\x14.kvpb.UnwatchRequest\x1a\x15.kvpb.UnwatchResponse\x12E\n" +
	"\fGetWatchList\x12\x19.kvpb.GetWatchListRequest\x1a\x1a.kvpb.GetWatchListResponse\x129\n" +
	"\bGetStats\x12\x15.kvpb.GetStatsRequest\x1a\x16.kvpb.GetStatsResponseB\x13Z\x11kv/pkg/proto/kvpbb\x06proto3"

var file_pkg_proto_kvpb_service_kvservice_proto_goTypes = []any{
	(*GetRequest)(nil),              // 0: kvpb.GetRequest
	(*PutRequest)(nil),              // 1: kvpb.PutRequest
	(*DeleteRequest)(nil),           // 2: kvpb.DeleteRequest
	(*PutWithTTLRequest)(nil),       // 3: kvpb.PutWithTTLRequest
	(*GetWithRevisionRequest)(nil),  // 4: kvpb.GetWithRevisionRequest
	(*GetHistoryRequest)(nil),       // 5: kvpb.GetHistoryRequest
	(*RangeRequest)(nil),            // 6: kvpb.RangeRequest
	(*CompactRequest)(nil),          // 7: kvpb.CompactRequest
	(*TxnRequest)(nil),              // 8: kvpb.TxnRequest
	(*WatchRequest)(nil),            // 9: kvpb.WatchRequest
	(*UnwatchRequest)(nil),          // 10: kvpb.UnwatchRequest
	(*GetWatchListRequest)(nil),     // 11: kvpb.GetWatchListRequest
	(*GetStatsRequest)(nil),         // 12: kvpb.GetStatsRequest
	(*GetResponse)(nil),             // 13: kvpb.GetResponse
	(*PutResponse)(nil),             // 14: kvpb.PutResponse
	(*DeleteResponse)(nil),          // 15: kvpb.DeleteResponse
	(*GetWithRevisionResponse)(nil), // 16: kvpb.GetWithRevisionResponse
	(*GetHistoryResponse)(nil),      // 17: kvpb.GetHistoryResponse
	(*RangeResponse)(nil),           // 18: kvpb.RangeResponse
	(*CompactResponse)(nil),         // 19: kvpb.CompactResponse
	(*TxnResponse)(nil),             // 20: kvpb.TxnResponse
	(*WatchEvent)(nil),              // 21: kvpb.WatchEvent
	(*UnwatchResponse)(nil),         // 22: kvpb.UnwatchResponse
	(*GetWatchListResponse)(nil),    // 23: kvpb.GetWatchListResponse
	(*GetStatsResponse)(nil),        // 24: kvpb.GetStatsResponse
}
var file_pkg_proto_kvpb_service_kvservice_proto_depIdxs = []int32{
	0,  // 0: kvpb.KVService.Get:input_type -> kvpb.GetRequest
	1,  // 1: kvpb.KVService.Put:input_type -> kvpb.PutRequest
	2,  // 2: kvpb.KVService.Delete:input_type -> kvpb.DeleteRequest
	3,  // 3: kvpb.KVService.PutWithTTL:input_type -> kvpb.PutWithTTLRequest
	4,  // 4: kvpb.KVService.GetWithRevision:input_type -> kvpb.GetWithRevisionRequest
	5,  // 5: kvpb.KVService.GetHistory:input_type -> kvpb.GetHistoryRequest
	6,  // 6: kvpb.KVService.Range:input_type -> kvpb.RangeRequest
	7,  // 7: kvpb.KVService.Compact:input_type -> kvpb.CompactRequest
	8,  // 8: kvpb.KVService.Txn:input_type -> kvpb.TxnRequest
	9,  // 9: kvpb.KVService.Watch:input_type -> kvpb.WatchRequest
	10, // 10: kvpb.KVService.Unwatch:input_type -> kvpb.UnwatchRequest
	11, // 11: kvpb.KVService.GetWatchList:input_type -> kvpb.GetWatchListRequest
	12, // 12: kvpb.KVService.GetStats:input_type -> kvpb.GetStatsRequest
	13, // 13: kvpb.KVService.Get:output_type -> kvpb.GetResponse
	14, // 14: kvpb.KVService.Put:output_type -> kvpb.PutResponse
	15, // 15: kvpb.KVService.Delete:output_type -> kvpb.DeleteResponse
	14, // 16: kvpb.KVService.PutWithTTL:output_type -> kvpb.PutResponse
	16, // 17: kvpb.KVService.GetWithRevision:output_type -> kvpb.GetWithRevisionResponse
	17, // 18: kvpb.KVService.GetHistory:output_type -> kvpb.GetHistoryResponse
	18, // 19: kvpb.KVService.Range:output_type -> kvpb.RangeResponse
	19, // 20: kvpb.KVService.Compact:output_type -> kvpb.CompactResponse
	20, // 21: kvpb.KVService.Txn:output_type -> kvpb.TxnResponse
	21, // 22: kvpb.KVService.Watch:output_type -> kvpb.WatchEvent
	22, // 23: kvpb.KVService.Unwatch:output_type -> kvpb.UnwatchResponse
	23, // 24: kvpb.KVService.GetWatchList:output_type -> kvpb.GetWatchListResponse
	24, // 25: kvpb.KVService.GetStats:output_type -> kvpb.GetStatsResponse
	13, // [13:26] is the sub-list for method output_type
	0,  // [0:13] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_kvpb_service_kvservice_proto_init() }
func file_pkg_proto_kvpb_service_kvservice_proto_init() {
	if File_pkg_proto_kvpb_service_kvservice_proto != nil {
		return
	}
	file_pkg_proto_kvpb_common_requests_proto_init()
	file_pkg_proto_kvpb_common_responses_proto_init()
	file_pkg_proto_kvpb_kv_kv_proto_init()
	file_pkg_proto_kvpb_transaction_transaction_proto_init()
	file_pkg_proto_kvpb_watch_watch_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_kvpb_service_kvservice_proto_rawDesc), len(file_pkg_proto_kvpb_service_kvservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_kvpb_service_kvservice_proto_goTypes,
		DependencyIndexes: file_pkg_proto_kvpb_service_kvservice_proto_depIdxs,
	}.Build()
	File_pkg_proto_kvpb_service_kvservice_proto = out.File
	file_pkg_proto_kvpb_service_kvservice_proto_goTypes = nil
	file_pkg_proto_kvpb_service_kvservice_proto_depIdxs = nil
}
