// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pkg/proto/kvpb/common/requests.proto

package kvpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetRequest 获取键值对请求
type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // 要获取的键
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_pkg_proto_kvpb_common_requests_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_kvpb_common_requests_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_kvpb_common_requests_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// PutRequest 设置键值对请求
type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`     // 键
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // 值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_pkg_proto_kvpb_common_requests_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_kvpb_common_requests_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_kvpb_common_requests_proto_rawDescGZIP(), []int{1}
}

func (x *PutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// DeleteRequest 删除键值对请求
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // 要删除的键
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_pkg_proto_kvpb_common_requests_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_kvpb_common_requests_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_kvpb_common_requests_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// PutWithTTLRequest 设置带TTL的键值对请求
type PutWithTTLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`     // 键
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // 值
	Ttl           int64                  `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`    // TTL（秒），0表示永不过期
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutWithTTLRequest) Reset() {
	*x = PutWithTTLRequest{}
	mi := &file_pkg_proto_kvpb_common_requests_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutWithTTLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutWithTTLRequest) ProtoMessage() {}

func (x *PutWithTTLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_kvpb_common_requests_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutWithTTLRequest.ProtoReflect.Descriptor instead.
func (*PutWithTTLRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_kvpb_common_requests_proto_rawDescGZIP(), []int{3}
}

func (x *PutWithTTLRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutWithTTLRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *PutWithTTLRequest) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

// GetWithRevisionRequest 获取指定版本的键值对请求
type GetWithRevisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`            // 键
	Revision      int64                  `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"` // 版本号，0表示最新版本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWithRevisionRequest) Reset() {
	*x = GetWithRevisionRequest{}
	mi := &file_pkg_proto_kvpb_common_requests_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWithRevisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWithRevisionRequest) ProtoMessage() {}

func (x *GetWithRevisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_kvpb_common_requests_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWithRevisionRequest.ProtoReflect.Descriptor instead.
func (*GetWithRevisionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_kvpb_common_requests_proto_rawDescGZIP(), []int{4}
}

func (x *GetWithRevisionRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetWithRevisionRequest) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

// GetHistoryRequest 获取键历史版本请求
type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`      // 键
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // 返回历史版本数量限制
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_pkg_proto_kvpb_common_requests_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_kvpb_common_requests_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_kvpb_common_requests_proto_rawDescGZIP(), []int{5}
}

func (x *GetHistoryRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetHistoryRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// UnwatchRequest 取消监听请求
type UnwatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WatcherId     string                 `protobuf:"bytes,1,opt,name=watcher_id,json=watcherId,proto3" json:"watcher_id,omitempty"` // 监听器ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnwatchRequest) Reset() {
	*x = UnwatchRequest{}
	mi := &file_pkg_proto_kvpb_common_requests_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnwatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnwatchRequest) ProtoMessage() {}

func (x *UnwatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_kvpb_common_requests_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnwatchRequest.ProtoReflect.Descriptor instead.
func (*UnwatchRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_kvpb_common_requests_proto_rawDescGZIP(), []int{6}
}

func (x *UnwatchRequest) GetWatcherId() string {
	if x != nil {
		return x.WatcherId
	}
	return ""
}

// GetStatsRequest 获取统计信息请求
type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_pkg_proto_kvpb_common_requests_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_kvpb_common_requests_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_kvpb_common_requests_proto_rawDescGZIP(), []int{7}
}

var File_pkg_proto_kvpb_common_requests_proto protoreflect.FileDescriptor

const file_pkg_proto_kvpb_common_requests_proto_rawDesc = "" +
	"\n" +
	"$pkg/proto/kvpb/common/requests.proto\x12\x04kvpb\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"4\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"M\n" +
	"\x11PutWithTTLRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\x03R\x03ttl\"F\n" +
	"\x16GetWithRevisionRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x03R\brevision\";\n" +
	"\x11GetHistoryRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\"/\n" +
	"\x0eUnwatchRequest\x12\x1d\n" +
	"\n" +
	"watcher_id\x18\x01 \x01(\tR\twatcherId\"\x11\n" +
	"\x0fGetStatsRequestB\x13Z\x11kv/pkg/proto/kvpbb\x06proto3"

var (
	file_pkg_proto_kvpb_common_requests_proto_rawDescOnce sync.Once
	file_pkg_proto_kvpb_common_requests_proto_rawDescData []byte
)

func file_pkg_proto_kvpb_common_requests_proto_rawDescGZIP() []byte {
	file_pkg_proto_kvpb_common_requests_proto_rawDescOnce.Do(func() {
		file_pkg_proto_kvpb_common_requests_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_kvpb_common_requests_proto_rawDesc), len(file_pkg_proto_kvpb_common_requests_proto_rawDesc)))
	})
	return file_pkg_proto_kvpb_common_requests_proto_rawDescData
}

var file_pkg_proto_kvpb_common_requests_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_proto_kvpb_common_requests_proto_goTypes = []any{
	(*GetRequest)(nil),             // 0: kvpb.GetRequest
	(*PutRequest)(nil),             // 1: kvpb.PutRequest
	(*DeleteRequest)(nil),          // 2: kvpb.DeleteRequest
	(*PutWithTTLRequest)(nil),      // 3: kvpb.PutWithTTLRequest
	(*GetWithRevisionRequest)(nil), // 4: kvpb.GetWithRevisionRequest
	(*GetHistoryRequest)(nil),      // 5: kvpb.GetHistoryRequest
	(*UnwatchRequest)(nil),         // 6: kvpb.UnwatchRequest
	(*GetStatsRequest)(nil),        // 7: kvpb.GetStatsRequest
}
var file_pkg_proto_kvpb_common_requests_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_kvpb_common_requests_proto_init() }
func file_pkg_proto_kvpb_common_requests_proto_init() {
	if File_pkg_proto_kvpb_common_requests_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_kvpb_common_requests_proto_rawDesc), len(file_pkg_proto_kvpb_common_requests_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_kvpb_common_requests_proto_goTypes,
		DependencyIndexes: file_pkg_proto_kvpb_common_requests_proto_depIdxs,
		MessageInfos:      file_pkg_proto_kvpb_common_requests_proto_msgTypes,
	}.Build()
	File_pkg_proto_kvpb_common_requests_proto = out.File
	file_pkg_proto_kvpb_common_requests_proto_goTypes = nil
	file_pkg_proto_kvpb_common_requests_proto_depIdxs = nil
}
