// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pkg/proto/kvpb/common/responses.proto

package kvpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetResponse 获取键值对响应
type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`    // 值
	Exists        bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"` // 键是否存在
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`    // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_pkg_proto_kvpb_common_responses_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_kvpb_common_responses_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_kvpb_common_responses_proto_rawDescGZIP(), []int{0}
}

func (x *GetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *GetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// PutResponse 设置键值对响应
type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      int64                  `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"` // 版本号
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`        // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_pkg_proto_kvpb_common_responses_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_kvpb_common_responses_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_kvpb_common_responses_proto_rawDescGZIP(), []int{1}
}

func (x *PutResponse) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *PutResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// DeleteResponse 删除键值对响应
type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      int64                  `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"` // 版本号
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`        // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_pkg_proto_kvpb_common_responses_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_kvpb_common_responses_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_kvpb_common_responses_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteResponse) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *DeleteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GetWithRevisionResponse 获取指定版本的键值对响应
type GetWithRevisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`        // 值
	Revision      int64                  `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"` // 版本号
	Exists        bool                   `protobuf:"varint,3,opt,name=exists,proto3" json:"exists,omitempty"`     // 键是否存在
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`        // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWithRevisionResponse) Reset() {
	*x = GetWithRevisionResponse{}
	mi := &file_pkg_proto_kvpb_common_responses_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWithRevisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWithRevisionResponse) ProtoMessage() {}

func (x *GetWithRevisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_kvpb_common_responses_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWithRevisionResponse.ProtoReflect.Descriptor instead.
func (*GetWithRevisionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_kvpb_common_responses_proto_rawDescGZIP(), []int{3}
}

func (x *GetWithRevisionResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetWithRevisionResponse) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *GetWithRevisionResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *GetWithRevisionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GetHistoryResponse 获取键历史版本响应
type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*VersionedKVPair     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // 历史版本列表
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_pkg_proto_kvpb_common_responses_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_kvpb_common_responses_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_kvpb_common_responses_proto_rawDescGZIP(), []int{4}
}

func (x *GetHistoryResponse) GetItems() []*VersionedKVPair {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetHistoryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// UnwatchResponse 取消监听响应
type UnwatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`      // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnwatchResponse) Reset() {
	*x = UnwatchResponse{}
	mi := &file_pkg_proto_kvpb_common_responses_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnwatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnwatchResponse) ProtoMessage() {}

func (x *UnwatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_kvpb_common_responses_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnwatchResponse.ProtoReflect.Descriptor instead.
func (*UnwatchResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_kvpb_common_responses_proto_rawDescGZIP(), []int{5}
}

func (x *UnwatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnwatchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GetStatsResponse 获取统计信息响应
type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         map[string]string      `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 统计信息
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                                                                           // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_pkg_proto_kvpb_common_responses_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_kvpb_common_responses_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_kvpb_common_responses_proto_rawDescGZIP(), []int{6}
}

func (x *GetStatsResponse) GetStats() map[string]string {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *GetStatsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_proto_kvpb_common_responses_proto protoreflect.FileDescriptor

const file_pkg_proto_kvpb_common_responses_proto_rawDesc = "" +
	"\n" +
	"%pkg/proto/kvpb/common/responses.proto\x12\x04kvpb\x1a\x1apkg/proto/kvpb/kv/kv.proto\"Q\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"?\n" +
	"\vPutResponse\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x03R\brevision\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"B\n" +
	"\x0eDeleteResponse\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x03R\brevision\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"y\n" +
	"\x17GetWithRevisionResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x03R\brevision\x12\x16\n" +
	"\x06exists\x18\x03 \x01(\bR\x06exists\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"W\n" +
	"\x12GetHistoryResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.kvpb.VersionedKVPairR\x05items\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"A\n" +
	"\x0fUnwatchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x9b\x01\n" +
	"\x10GetStatsResponse\x127\n" +
	"\x05stats\x18\x01 \x03(\v2!.kvpb.GetStatsResponse.StatsEntryR\x05stats\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x1a8\n" +
	"\n" +
	"StatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x13Z\x11kv/pkg/proto/kvpbb\x06proto3"

var (
	file_pkg_proto_kvpb_common_responses_proto_rawDescOnce sync.Once
	file_pkg_proto_kvpb_common_responses_proto_rawDescData []byte
)

func file_pkg_proto_kvpb_common_responses_proto_rawDescGZIP() []byte {
	file_pkg_proto_kvpb_common_responses_proto_rawDescOnce.Do(func() {
		file_pkg_proto_kvpb_common_responses_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_kvpb_common_responses_proto_rawDesc), len(file_pkg_proto_kvpb_common_responses_proto_rawDesc)))
	})
	return file_pkg_proto_kvpb_common_responses_proto_rawDescData
}

var file_pkg_proto_kvpb_common_responses_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_proto_kvpb_common_responses_proto_goTypes = []any{
	(*GetResponse)(nil),             // 0: kvpb.GetResponse
	(*PutResponse)(nil),             // 1: kvpb.PutResponse
	(*DeleteResponse)(nil),          // 2: kvpb.DeleteResponse
	(*GetWithRevisionResponse)(nil), // 3: kvpb.GetWithRevisionResponse
	(*GetHistoryResponse)(nil),      // 4: kvpb.GetHistoryResponse
	(*UnwatchResponse)(nil),         // 5: kvpb.UnwatchResponse
	(*GetStatsResponse)(nil),        // 6: kvpb.GetStatsResponse
	nil,                             // 7: kvpb.GetStatsResponse.StatsEntry
	(*VersionedKVPair)(nil),         // 8: kvpb.VersionedKVPair
}
var file_pkg_proto_kvpb_common_responses_proto_depIdxs = []int32{
	8, // 0: kvpb.GetHistoryResponse.items:type_name -> kvpb.VersionedKVPair
	7, // 1: kvpb.GetStatsResponse.stats:type_name -> kvpb.GetStatsResponse.StatsEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_proto_kvpb_common_responses_proto_init() }
func file_pkg_proto_kvpb_common_responses_proto_init() {
	if File_pkg_proto_kvpb_common_responses_proto != nil {
		return
	}
	file_pkg_proto_kvpb_kv_kv_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_kvpb_common_responses_proto_rawDesc), len(file_pkg_proto_kvpb_common_responses_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_kvpb_common_responses_proto_goTypes,
		DependencyIndexes: file_pkg_proto_kvpb_common_responses_proto_depIdxs,
		MessageInfos:      file_pkg_proto_kvpb_common_responses_proto_msgTypes,
	}.Build()
	File_pkg_proto_kvpb_common_responses_proto = out.File
	file_pkg_proto_kvpb_common_responses_proto_goTypes = nil
	file_pkg_proto_kvpb_common_responses_proto_depIdxs = nil
}
