// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pkg/proto/kvpb/transaction/transaction.proto

package kvpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CompareResult 比较操作类型
type CompareResult int32

const (
	CompareResult_EQUAL         CompareResult = 0 // 等于
	CompareResult_GREATER       CompareResult = 1 // 大于
	CompareResult_LESS          CompareResult = 2 // 小于
	CompareResult_NOT_EQUAL     CompareResult = 3 // 不等于
	CompareResult_GREATER_EQUAL CompareResult = 4 // 大于等于
	CompareResult_LESS_EQUAL    CompareResult = 5 // 小于等于
)

// Enum value maps for CompareResult.
var (
	CompareResult_name = map[int32]string{
		0: "EQUAL",
		1: "GREATER",
		2: "LESS",
		3: "NOT_EQUAL",
		4: "GREATER_EQUAL",
		5: "LESS_EQUAL",
	}
	CompareResult_value = map[string]int32{
		"EQUAL":         0,
		"GREATER":       1,
		"LESS":          2,
		"NOT_EQUAL":     3,
		"GREATER_EQUAL": 4,
		"LESS_EQUAL":    5,
	}
)

func (x CompareResult) Enum() *CompareResult {
	p := new(CompareResult)
	*p = x
	return p
}

func (x CompareResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompareResult) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_kvpb_transaction_transaction_proto_enumTypes[0].Descriptor()
}

func (CompareResult) Type() protoreflect.EnumType {
	return &file_pkg_proto_kvpb_transaction_transaction_proto_enumTypes[0]
}

func (x CompareResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompareResult.Descriptor instead.
func (CompareResult) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_kvpb_transaction_transaction_proto_rawDescGZIP(), []int{0}
}

// CompareTarget 比较目标类型
type CompareTarget int32

const (
	CompareTarget_VERSION CompareTarget = 0 // 版本号
	CompareTarget_CREATE  CompareTarget = 1 // 创建版本
	CompareTarget_MOD     CompareTarget = 2 // 修改版本
	CompareTarget_VALUE   CompareTarget = 3 // 值
	CompareTarget_EXISTS  CompareTarget = 4 // 是否存在
)

// Enum value maps for CompareTarget.
var (
	CompareTarget_name = map[int32]string{
		0: "VERSION",
		1: "CREATE",
		2: "MOD",
		3: "VALUE",
		4: "EXISTS",
	}
	CompareTarget_value = map[string]int32{
		"VERSION": 0,
		"CREATE":  1,
		"MOD":     2,
		"VALUE":   3,
		"EXISTS":  4,
	}
)

func (x CompareTarget) Enum() *CompareTarget {
	p := new(CompareTarget)
	*p = x
	return p
}

func (x CompareTarget) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompareTarget) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_kvpb_transaction_transaction_proto_enumTypes[1].Descriptor()
}

func (CompareTarget) Type() protoreflect.EnumType {
	return &file_pkg_proto_kvpb_transaction_transaction_proto_enumTypes[1]
}

func (x CompareTarget) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompareTarget.Descriptor instead.
func (CompareTarget) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_kvpb_transaction_transaction_proto_rawDescGZIP(), []int{1}
}

// Compare 单个比较条件
type Compare struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`                                // 要比较的键
	Target        CompareTarget          `protobuf:"varint,2,opt,name=target,proto3,enum=kvpb.CompareTarget" json:"target,omitempty"` // 比较目标
	Result        CompareResult          `protobuf:"varint,3,opt,name=result,proto3,enum=kvpb.CompareResult" json:"result,omitempty"` // 比较结果
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`                            // 比较值（用于VALUE比较）
	Version       int64                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`                       // 版本号（用于版本比较）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Compare) Reset() {
	*x = Compare{}
	mi := &file_pkg_proto_kvpb_transaction_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Compare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Compare) ProtoMessage() {}

func (x *Compare) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_kvpb_transaction_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Compare.ProtoReflect.Descriptor instead.
func (*Compare) Descriptor() ([]byte, []int) {
	return file_pkg_proto_kvpb_transaction_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *Compare) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Compare) GetTarget() CompareTarget {
	if x != nil {
		return x.Target
	}
	return CompareTarget_VERSION
}

func (x *Compare) GetResult() CompareResult {
	if x != nil {
		return x.Result
	}
	return CompareResult_EQUAL
}

func (x *Compare) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Compare) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// TxnRequest 事务请求
type TxnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Compare       []*Compare             `protobuf:"bytes,1,rep,name=compare,proto3" json:"compare,omitempty"` // 比较条件
	Success       []*Op                  `protobuf:"bytes,2,rep,name=success,proto3" json:"success,omitempty"` // 成功时执行的操作
	Failure       []*Op                  `protobuf:"bytes,3,rep,name=failure,proto3" json:"failure,omitempty"` // 失败时执行的操作
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxnRequest) Reset() {
	*x = TxnRequest{}
	mi := &file_pkg_proto_kvpb_transaction_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnRequest) ProtoMessage() {}

func (x *TxnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_kvpb_transaction_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnRequest.ProtoReflect.Descriptor instead.
func (*TxnRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_kvpb_transaction_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *TxnRequest) GetCompare() []*Compare {
	if x != nil {
		return x.Compare
	}
	return nil
}

func (x *TxnRequest) GetSuccess() []*Op {
	if x != nil {
		return x.Success
	}
	return nil
}

func (x *TxnRequest) GetFailure() []*Op {
	if x != nil {
		return x.Failure
	}
	return nil
}

// TxnResponse 事务响应
type TxnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Succeeded     bool                   `protobuf:"varint,1,opt,name=succeeded,proto3" json:"succeeded,omitempty"` // 事务是否成功
	Responses     []*OpResponse          `protobuf:"bytes,2,rep,name=responses,proto3" json:"responses,omitempty"`  // 操作响应
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxnResponse) Reset() {
	*x = TxnResponse{}
	mi := &file_pkg_proto_kvpb_transaction_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnResponse) ProtoMessage() {}

func (x *TxnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_kvpb_transaction_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnResponse.ProtoReflect.Descriptor instead.
func (*TxnResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_kvpb_transaction_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *TxnResponse) GetSucceeded() bool {
	if x != nil {
		return x.Succeeded
	}
	return false
}

func (x *TxnResponse) GetResponses() []*OpResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

// OpResponse 操作响应
type OpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`          // 键
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`      // 值
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"` // 版本号
	Exists        bool                   `protobuf:"varint,4,opt,name=exists,proto3" json:"exists,omitempty"`   // 是否存在
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`      // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpResponse) Reset() {
	*x = OpResponse{}
	mi := &file_pkg_proto_kvpb_transaction_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpResponse) ProtoMessage() {}

func (x *OpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_kvpb_transaction_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpResponse.ProtoReflect.Descriptor instead.
func (*OpResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_kvpb_transaction_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *OpResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OpResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *OpResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *OpResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *OpResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_proto_kvpb_transaction_transaction_proto protoreflect.FileDescriptor

const file_pkg_proto_kvpb_transaction_transaction_proto_rawDesc = "" +
	"\n" +
	",pkg/proto/kvpb/transaction/transaction.proto\x12\x04kvpb\x1a pkg/proto/kvpb/internal/op.proto\"\xa5\x01\n" +
	"\aCompare\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x06target\x18\x02 \x01(\x0e2\x13.kvpb.CompareTargetR\x06target\x12+\n" +
	"\x06result\x18\x03 \x01(\x0e2\x13.kvpb.CompareResultR\x06result\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\"}\n" +
	"\n" +
	"TxnRequest\x12'\n" +
	"\acompare\x18\x01 \x03(\v2\r.kvpb.CompareR\acompare\x12\"\n" +
	"\asuccess\x18\x02 \x03(\v2\b.kvpb.OpR\asuccess\x12\"\n" +
	"\afailure\x18\x03 \x03(\v2\b.kvpb.OpR\afailure\"[\n" +
	"\vTxnResponse\x12\x1c\n" +
	"\tsucceeded\x18\x01 \x01(\bR\tsucceeded\x12.\n" +
	"\tresponses\x18\x02 \x03(\v2\x10.kvpb.OpResponseR\tresponses\"|\n" +
	"\n" +
	"OpResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12\x16\n" +
	"\x06exists\x18\x04 \x01(\bR\x06exists\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error*c\n" +
	"\rCompareResult\x12\t\n" +
	"\x05EQUAL\x10\x00\x12\v\n" +
	"\aGREATER\x10\x01\x12\b\n" +
	"\x04LESS\x10\x02\x12\r\n" +
	"\tNOT_EQUAL\x10\x03\x12\x11\n" +
	"\rGREATER_EQUAL\x10\x04\x12\x0e\n" +
	"\n" +
	"LESS_EQUAL\x10\x05*H\n" +
	"\rCompareTarget\x12\v\n" +
	"\aVERSION\x10\x00\x12\n" +
	"\n" +
	"\x06CREATE\x10\x01\x12\a\n" +
	"\x03MOD\x10\x02\x12\t\n" +
	"\x05VALUE\x10\x03\x12\n" +
	"\n" +
	"\x06EXISTS\x10\x04B\x13Z\x11kv/pkg/proto/kvpbb\x06proto3"

var (
	file_pkg_proto_kvpb_transaction_transaction_proto_rawDescOnce sync.Once
	file_pkg_proto_kvpb_transaction_transaction_proto_rawDescData []byte
)

func file_pkg_proto_kvpb_transaction_transaction_proto_rawDescGZIP() []byte {
	file_pkg_proto_kvpb_transaction_transaction_proto_rawDescOnce.Do(func() {
		file_pkg_proto_kvpb_transaction_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_kvpb_transaction_transaction_proto_rawDesc), len(file_pkg_proto_kvpb_transaction_transaction_proto_rawDesc)))
	})
	return file_pkg_proto_kvpb_transaction_transaction_proto_rawDescData
}

var file_pkg_proto_kvpb_transaction_transaction_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_proto_kvpb_transaction_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_proto_kvpb_transaction_transaction_proto_goTypes = []any{
	(CompareResult)(0),  // 0: kvpb.CompareResult
	(CompareTarget)(0),  // 1: kvpb.CompareTarget
	(*Compare)(nil),     // 2: kvpb.Compare
	(*TxnRequest)(nil),  // 3: kvpb.TxnRequest
	(*TxnResponse)(nil), // 4: kvpb.TxnResponse
	(*OpResponse)(nil),  // 5: kvpb.OpResponse
	(*Op)(nil),          // 6: kvpb.Op
}
var file_pkg_proto_kvpb_transaction_transaction_proto_depIdxs = []int32{
	1, // 0: kvpb.Compare.target:type_name -> kvpb.CompareTarget
	0, // 1: kvpb.Compare.result:type_name -> kvpb.CompareResult
	2, // 2: kvpb.TxnRequest.compare:type_name -> kvpb.Compare
	6, // 3: kvpb.TxnRequest.success:type_name -> kvpb.Op
	6, // 4: kvpb.TxnRequest.failure:type_name -> kvpb.Op
	5, // 5: kvpb.TxnResponse.responses:type_name -> kvpb.OpResponse
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_proto_kvpb_transaction_transaction_proto_init() }
func file_pkg_proto_kvpb_transaction_transaction_proto_init() {
	if File_pkg_proto_kvpb_transaction_transaction_proto != nil {
		return
	}
	file_pkg_proto_kvpb_internal_op_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_kvpb_transaction_transaction_proto_rawDesc), len(file_pkg_proto_kvpb_transaction_transaction_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_kvpb_transaction_transaction_proto_goTypes,
		DependencyIndexes: file_pkg_proto_kvpb_transaction_transaction_proto_depIdxs,
		EnumInfos:         file_pkg_proto_kvpb_transaction_transaction_proto_enumTypes,
		MessageInfos:      file_pkg_proto_kvpb_transaction_transaction_proto_msgTypes,
	}.Build()
	File_pkg_proto_kvpb_transaction_transaction_proto = out.File
	file_pkg_proto_kvpb_transaction_transaction_proto_goTypes = nil
	file_pkg_proto_kvpb_transaction_transaction_proto_depIdxs = nil
}
