// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pkg/proto/kvpb/wal.proto

package kvpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WAL entry类型
type EntryType int32

const (
	EntryType_ENTRY_NORMAL      EntryType = 0
	EntryType_ENTRY_CONF_CHANGE EntryType = 1
	EntryType_ENTRY_META        EntryType = 2
)

// Enum value maps for EntryType.
var (
	EntryType_name = map[int32]string{
		0: "ENTRY_NORMAL",
		1: "ENTRY_CONF_CHANGE",
		2: "ENTRY_META",
	}
	EntryType_value = map[string]int32{
		"ENTRY_NORMAL":      0,
		"ENTRY_CONF_CHANGE": 1,
		"ENTRY_META":        2,
	}
)

func (x EntryType) Enum() *EntryType {
	p := new(EntryType)
	*p = x
	return p
}

func (x EntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_kvpb_wal_proto_enumTypes[0].Descriptor()
}

func (EntryType) Type() protoreflect.EnumType {
	return &file_pkg_proto_kvpb_wal_proto_enumTypes[0]
}

func (x EntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryType.Descriptor instead.
func (EntryType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_kvpb_wal_proto_rawDescGZIP(), []int{0}
}

// WAL分段的单条entry
type WALEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Index         uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Type          EntryType              `protobuf:"varint,3,opt,name=type,proto3,enum=kvpb.EntryType" json:"type,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"` // raft entry、kv op等protobuf序列化内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WALEntry) Reset() {
	*x = WALEntry{}
	mi := &file_pkg_proto_kvpb_wal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WALEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALEntry) ProtoMessage() {}

func (x *WALEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_kvpb_wal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALEntry.ProtoReflect.Descriptor instead.
func (*WALEntry) Descriptor() ([]byte, []int) {
	return file_pkg_proto_kvpb_wal_proto_rawDescGZIP(), []int{0}
}

func (x *WALEntry) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *WALEntry) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *WALEntry) GetType() EntryType {
	if x != nil {
		return x.Type
	}
	return EntryType_ENTRY_NORMAL
}

func (x *WALEntry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_pkg_proto_kvpb_wal_proto protoreflect.FileDescriptor

const file_pkg_proto_kvpb_wal_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/proto/kvpb/wal.proto\x12\x04kvpb\"m\n" +
	"\bWALEntry\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\x12#\n" +
	"\x04type\x18\x03 \x01(\x0e2\x0f.kvpb.EntryTypeR\x04type\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data*D\n" +
	"\tEntryType\x12\x10\n" +
	"\fENTRY_NORMAL\x10\x00\x12\x15\n" +
	"\x11ENTRY_CONF_CHANGE\x10\x01\x12\x0e\n" +
	"\n" +
	"ENTRY_META\x10\x02B\x13Z\x11kv/proto/pkg/kvpbb\x06proto3"

var (
	file_pkg_proto_kvpb_wal_proto_rawDescOnce sync.Once
	file_pkg_proto_kvpb_wal_proto_rawDescData []byte
)

func file_pkg_proto_kvpb_wal_proto_rawDescGZIP() []byte {
	file_pkg_proto_kvpb_wal_proto_rawDescOnce.Do(func() {
		file_pkg_proto_kvpb_wal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_kvpb_wal_proto_rawDesc), len(file_pkg_proto_kvpb_wal_proto_rawDesc)))
	})
	return file_pkg_proto_kvpb_wal_proto_rawDescData
}

var file_pkg_proto_kvpb_wal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_kvpb_wal_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_proto_kvpb_wal_proto_goTypes = []any{
	(EntryType)(0),   // 0: kvpb.EntryType
	(*WALEntry)(nil), // 1: kvpb.WALEntry
}
var file_pkg_proto_kvpb_wal_proto_depIdxs = []int32{
	0, // 0: kvpb.WALEntry.type:type_name -> kvpb.EntryType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_kvpb_wal_proto_init() }
func file_pkg_proto_kvpb_wal_proto_init() {
	if File_pkg_proto_kvpb_wal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_kvpb_wal_proto_rawDesc), len(file_pkg_proto_kvpb_wal_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_kvpb_wal_proto_goTypes,
		DependencyIndexes: file_pkg_proto_kvpb_wal_proto_depIdxs,
		EnumInfos:         file_pkg_proto_kvpb_wal_proto_enumTypes,
		MessageInfos:      file_pkg_proto_kvpb_wal_proto_msgTypes,
	}.Build()
	File_pkg_proto_kvpb_wal_proto = out.File
	file_pkg_proto_kvpb_wal_proto_goTypes = nil
	file_pkg_proto_kvpb_wal_proto_depIdxs = nil
}
