// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pkg/proto/kvpb/watch/watch.proto

package kvpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WatchRequest Watch监听请求
type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`                              // 要监听的键
	Prefix        string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`                        // 要监听的前缀
	WatcherId     string                 `protobuf:"bytes,3,opt,name=watcher_id,json=watcherId,proto3" json:"watcher_id,omitempty"` // 监听器ID（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_pkg_proto_kvpb_watch_watch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_kvpb_watch_watch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_kvpb_watch_watch_proto_rawDescGZIP(), []int{0}
}

func (x *WatchRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WatchRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *WatchRequest) GetWatcherId() string {
	if x != nil {
		return x.WatcherId
	}
	return ""
}

// WatchEvent Watch事件
type WatchEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`           // 事件类型：0=PUT, 1=DELETE, 2=EXPIRE
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`              // 键名
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`          // 值
	Revision      int64                  `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty"`   // 版本号
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 时间戳
	Ttl           int64                  `protobuf:"varint,6,opt,name=ttl,proto3" json:"ttl,omitempty"`             // TTL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEvent) Reset() {
	*x = WatchEvent{}
	mi := &file_pkg_proto_kvpb_watch_watch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEvent) ProtoMessage() {}

func (x *WatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_kvpb_watch_watch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEvent.ProtoReflect.Descriptor instead.
func (*WatchEvent) Descriptor() ([]byte, []int) {
	return file_pkg_proto_kvpb_watch_watch_proto_rawDescGZIP(), []int{1}
}

func (x *WatchEvent) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *WatchEvent) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WatchEvent) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *WatchEvent) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *WatchEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *WatchEvent) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

var File_pkg_proto_kvpb_watch_watch_proto protoreflect.FileDescriptor

const file_pkg_proto_kvpb_watch_watch_proto_rawDesc = "" +
	"\n" +
	" pkg/proto/kvpb/watch/watch.proto\x12\x04kvpb\"W\n" +
	"\fWatchRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12\x1d\n" +
	"\n" +
	"watcher_id\x18\x03 \x01(\tR\twatcherId\"\x94\x01\n" +
	"\n" +
	"WatchEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\x03R\brevision\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x10\n" +
	"\x03ttl\x18\x06 \x01(\x03R\x03ttlB\x13Z\x11kv/pkg/proto/kvpbb\x06proto3"

var (
	file_pkg_proto_kvpb_watch_watch_proto_rawDescOnce sync.Once
	file_pkg_proto_kvpb_watch_watch_proto_rawDescData []byte
)

func file_pkg_proto_kvpb_watch_watch_proto_rawDescGZIP() []byte {
	file_pkg_proto_kvpb_watch_watch_proto_rawDescOnce.Do(func() {
		file_pkg_proto_kvpb_watch_watch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_kvpb_watch_watch_proto_rawDesc), len(file_pkg_proto_kvpb_watch_watch_proto_rawDesc)))
	})
	return file_pkg_proto_kvpb_watch_watch_proto_rawDescData
}

var file_pkg_proto_kvpb_watch_watch_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_kvpb_watch_watch_proto_goTypes = []any{
	(*WatchRequest)(nil), // 0: kvpb.WatchRequest
	(*WatchEvent)(nil),   // 1: kvpb.WatchEvent
}
var file_pkg_proto_kvpb_watch_watch_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_kvpb_watch_watch_proto_init() }
func file_pkg_proto_kvpb_watch_watch_proto_init() {
	if File_pkg_proto_kvpb_watch_watch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_kvpb_watch_watch_proto_rawDesc), len(file_pkg_proto_kvpb_watch_watch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_kvpb_watch_watch_proto_goTypes,
		DependencyIndexes: file_pkg_proto_kvpb_watch_watch_proto_depIdxs,
		MessageInfos:      file_pkg_proto_kvpb_watch_watch_proto_msgTypes,
	}.Build()
	File_pkg_proto_kvpb_watch_watch_proto = out.File
	file_pkg_proto_kvpb_watch_watch_proto_goTypes = nil
	file_pkg_proto_kvpb_watch_watch_proto_depIdxs = nil
}
